#ifndef _ERROR_NUM_
#define _ERROR_NUM_

#define INTEGER_DIVIDE_BY_ZERO_PROTECTION 1
#define DEBUG_TRAP_BREAK_MONITOR 2
#define CPU_FAULT_ACTIVATE_GENERAL_PROTECTION 13
#define MEMORY_PAGE_FAULT_PAGE_UNREADY 14

#endif