#ifndef _ERROR_NUM_
#define _ERROR_NUM_

typedef enum {
    DIVIDE_BY_ZERO,
    DEBUG_EXCEPTION,
    NMI_INTERRUPT,
    BREAKPOINT,
    OVERFLOW,
    BOUND_RANGE_EXCEEDED,
    INVALID_OPCODE,
    DEVICE_NOT_AVAILABLE,
    DOUBLE_FAULT,
    INVALID_TSS,
    SEGMENT_NOT_PRESENT,
    STACK_SEGMENT_FAULT,
    GENERAL_PROTECTION_FAULT,
    PAGE_FAULT,
    FLOATING_POINT_ERROR,
    ALIGNMENT_CHECK,
    MACHINE_CHECK,
    SIMD_FLOATING_POINT_ERROR,
    VIRTUALIZATION_EXCEPTION,
    SECURITY_EXCEPTION,
    UNKNOWN_EXCEPTION,
    WATCHDOG_TIMEOUT_TIMER_EXCEPTION, // 21
    MEMORY_PAGE_FAULT_PAGE_UNREADY, // 22
    CPU_FAULT_ACTIVATE_GENERAL_PROTECTION, // 23
    KERNEL_PANIC_ERROR, // 24
    UNEXPECTED_KERNEL_ERROR, // 25
    FAILED_INITIALIZATION_USERLAND
} KernelPanic;

#endif